# docker-compose.yml
version: '3.8'

services:
  client:
    build:
      context: ./BolsaConsultaCliente
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - server

  server:
    build:
      context: ./BolsaConsultaServer
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "mysql://root:123456@localhost:3306/BolsaConsulta"
    ports:
      - "3000:3000"
    volumes:
      - ./BolsaConsultaServer/prisma:/app/prisma
